libsmbios: unused parameter
../common/smb_subr.c:73:28: error: unused parameter 'len' [-Werror,-Wunused-parameter]
smb_free(void *buf, size_t len)
                           ^
1 error generated.

../../../common/smbios/smb_info.c:667:45: error: unused parameter 'shp' [-Werror,-Wunused-parameter]
smbios_info_chassis_elts_free(smbios_hdl_t *shp, uint_t nents,
                                            ^
../../../common/smbios/smb_info.c:874:43: error: unused parameter 'shp' [-Werror,-Wunused-parameter]
smbios_info_slot_peers_free(smbios_hdl_t *shp, uint_t npeers,
                                          ^
../../../common/smbios/smb_info.c:2072:45: error: unused parameter 'shp' [-Werror,-Wunused-parameter]
smbios_info_fwinfo_comps_free(smbios_hdl_t *shp, uint_t ncomps,
                                            ^

Change-Id: I14a5568ec85a90e02cd7f076c0430656f6941607