libdevinfo: unused parameter
../devinfo_retire.c:107:27: error: unused parameter 'node' [-Werror,-Wunused-parameter]
enclosure_minor(di_node_t node, di_minor_t minor, void *arg)
                          ^
../devinfo_retire.c:107:44: error: unused parameter 'minor' [-Werror,-Wunused-parameter]
enclosure_minor(di_node_t node, di_minor_t minor, void *arg)
                                           ^
../devinfo_retire.c:149:21: error: unused parameter 'node' [-Werror,-Wunused-parameter]
smp_minor(di_node_t node, di_minor_t minor, void *arg)
                    ^
../devinfo_retire.c:149:38: error: unused parameter 'minor' [-Werror,-Wunused-parameter]
smp_minor(di_node_t node, di_minor_t minor, void *arg)
                                     ^
../devinfo_retire.c:184:22: error: unused parameter 'node' [-Werror,-Wunused-parameter]
disk_minor(di_node_t node, di_minor_t minor, void *arg)
                     ^
../devinfo_retire.c:421:24: error: unused parameter 'node' [-Werror,-Wunused-parameter]
call_offline(di_node_t node, di_minor_t minor, void *arg)
                       ^
6 errors generated.

../devinfo_dim.c:74:30: error: unused parameter 'dim' [-Werror,-Wunused-parameter]
di_dim_path_devices(di_dim_t dim, char *drv_name, int instance,
                             ^
1 error generated.

../devfsmap.c:175:28: error: unused parameter 'filep' [-Werror,-Wunused-parameter]
file_err(struct conf_file *filep, char *fmt, ...)
                           ^
../devfsmap.c:175:41: error: unused parameter 'fmt' [-Werror,-Wunused-parameter]
file_err(struct conf_file *filep, char *fmt, ...)
                                        ^
2 errors generated.

../devinfo_devlink.c:2204:53: error: unused parameter 'data' [-Werror,-Wunused-parameter]
cache_dev_link(struct di_devlink_handle *hdp, void *data, const char *link)
                                                    ^

../devfsinfo.c:1204:56: error: unused parameter 'node_stat' [-Werror,-Wunused-parameter]
check_logical_dev(const char *node, const struct stat *node_stat, int flags,
                                                       ^
../devfsinfo.c:1205:17: error: unused parameter 'ftw_info' [-Werror,-Wunused-parameter]
    struct FTW *ftw_info)
                ^
2 errors generated.

Change-Id: Id3913ab3c738c399c5cf71374a914cd78079ba19