libmapmalloc: unused parameter
../common/valloc.c:38:15: error: unused parameter 'size' [-Werror,-Wunused-parameter]
valloc(size_t size)
              ^
../common/valloc.c:50:17: error: unused parameter 'align' [-Werror,-Wunused-parameter]
memalign(size_t align, size_t nbytes)
                ^
../common/valloc.c:50:31: error: unused parameter 'nbytes' [-Werror,-Wunused-parameter]
memalign(size_t align, size_t nbytes)
                              ^
3 errors generated.

../common/calloc.c:62:23: error: unused parameter 'num' [-Werror,-Wunused-parameter]
cfree(void *p, size_t num, size_t size)
                      ^
../common/calloc.c:62:35: error: unused parameter 'size' [-Werror,-Wunused-parameter]
cfree(void *p, size_t num, size_t size)
                                  ^
2 errors generated.

Change-Id: I9f357d1cc48839385c174c09c064e88b5ec50390