libc: missing field
../port/stdio/data.c:68:68: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, _IOREAD, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                          ^
../port/stdio/data.c:69:67: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 1, _IOWRT, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                         ^
../port/stdio/data.c:71:18: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
                DEFAULTMBSTATE },
                               ^
../port/stdio/data.c:72:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:73:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:74:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:75:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:76:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:77:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:78:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:79:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:80:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:81:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:82:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:83:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:84:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:85:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:86:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
../port/stdio/data.c:87:62: error: missing field '_ops' initializer [-Werror,-Wmissing-field-initializers]
        { NULL, NULL, NULL, 0, 0, 0, RECURSIVEMUTEX, DEFAULTMBSTATE },
                                                                    ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

../port/locale/table.c:263:1: error: missing field '__runetype_ext' initializer [-Werror,-Wmissing-field-initializers]
};
^
1 error generated.

../port/gen/lckpwdf.c:53:4: error: missing field 'l_pad' initializer [-Werror,-Wmissing-field-initializers]
                        };
                        ^
1 error generated.

../port/gen/syslog.c:125:1: error: missing field '_LogDev' initializer [-Werror,-Wmissing-field-initializers]
};
^
1 error generated.

Change-Id: Ia8f8950dfd7e1eac3a9821ff07fad0be6f78b2e8