libsec: unused parameter
../common/aclcheck.c:301:31: error: unused parameter 'isdir' [-Werror,-Wunused-parameter]
ace_aclcheck(acl_t *aclp, int isdir)
                              ^
1 error generated.

Change-Id: Ia0349ae64d4ec21baf182f47e5f0886a5b837dea