libsocket: unused parameter
../inet/link_addr.c:48:67: error: unused parameter 'mactype' [-Werror,-Wunused-parameter]
_link_ntoa(const unsigned char *macaddr, char *str, int size, int mactype)
                                                                  ^
1 error generated.

../inet/ether_addr.c:183:71: error: unused parameter 'buflen' [-Werror,-Wunused-parameter]
str2ether(const char *instr, int lenstr, void *ent, char *buffer, int buflen)
                                                                      ^
1 error generated.

../inet/bootparams_getbyname.c:77:11: error: unused parameter 'ent' [-Werror,-Wunused-parameter]
    void *ent,          /* really (char *) */
          ^
1 error generated.

Change-Id: I5afe3c0902c383f41a7dbec48ba48065e76dd25d