iwi: unused variables
../../common/io/iwi/ipw2200.c: In function 'ipw2200_auth_and_assoc':
../../common/io/iwi/ipw2200.c:1629:14: error: variable 'wpa_level' set but not used [-Werror=unused-but-set-variable]
 1629 |  uint8_t    *wpa_level;
      |              ^~~~~~~~~
../../common/io/iwi/ipw2200.c: In function 'ipw2200_m_promisc':
../../common/io/iwi/ipw2200.c:2116:24: error: unused variable 'sc' [-Werror=unused-variable]
 2116 |  struct ipw2200_softc *sc = (struct ipw2200_softc *)arg;
      |                        ^~
../../common/io/iwi/ipw2200.c: In function 'ipw2200_intr':
../../common/io/iwi/ipw2200.c:2861:12: error: variable 'widx' set but not used [-Werror=unused-but-set-variable]
 2861 |  uint32_t  widx;
      |            ^~~~
cc1: all warnings being treated as errors
*** Error code 1
make: Fatal error: Command failed for target `obj64/ipw2200.o'
Current working directory /code/illumos-gate/usr/src/uts/intel/iwi

Change-Id: I0d52293611ca943bb3686845a8cb8cfe2a7424d6