libld: build errors with clang
/code/illumos-gate/usr/src/cmd/sgs/libld/common/files.c:406:2: error: variable '
flags1' is used uninitialized whenever switch default is taken [-Werror,-Wsometi
mes-uninitialized]
        default:
        ^~~~~~~
/code/illumos-gate/usr/src/cmd/sgs/libld/common/files.c:414:24: note: uninitiali
zed use occurs here
        if (ofl->ofl_flags1 & flags1) {
                              ^~~~~~
/code/illumos-gate/usr/src/cmd/sgs/libld/common/files.c:391:19: note: initialize
 the variable 'flags1' to silence this warning
        ofl_flag_t      flags1;
                              ^
                               = 0
1 error generated.

/code/illumos-gate/usr/src/cmd/sgs/libld/common/map_v2.c:1242:46: error: unused
parameter 'uvalue' [-Werror,-Wunused-parameter]
at_cap_hw_3(Mapfile *mf, Token eq_tok, void *uvalue)
                                             ^
1 error generated.

Change-Id: I11e199311cb5515faa5a45c4dbaf0d3d9eea7997