libsec: unused parameter
../common/acl_lex.l:46:21: error: unused parameter 's' [-Werror,-Wunused-parameter]
yyerror(const char *s)
                    ^

../../../common/acl/acl_common.c:225:32: error: unused parameter 'size' [-Werror,-Wunused-parameter]
cacl_realloc(void *ptr, size_t size, size_t new_size)
                               ^
../../../common/acl/acl_common.c:256:29: error: unused parameter 'size' [-Werror,-Wunused-parameter]
cacl_free(void *ptr, size_t size)
                            ^
2 errors generated.

Change-Id: Id68d9c2c0da593fbcab08854628da6e44086d251