snoop: unused label
snoop_socks.c: In function 'interpret_socks_call':
snoop_socks.c:246:1: error: label 'out' defined but not used [-Werror=unused-label]
 out:
 ^~~
snoop_socks.c: In function 'interpret_socks_reply':
snoop_socks.c:337:1: error: label 'out' defined but not used [-Werror=unused-label]
 out:
 ^~~
cc1: all warnings being treated as errors

Change-Id: Icd947c54d267279e30e6ac6705013752e1971600