libnsl: unused parameter
../key/publickey.c:119:46: error: unused parameter 'ent' [-Werror,-Wunused-parameter]
str2key(const char *instr, int lenstr, void *ent, char *buffer, int buflen)
                                             ^
../key/publickey.c:425:7: error: unused parameter 'pkeylen' [-Werror,-Wunused-parameter]
        int             pkeylen,        /* in  */
                        ^
../key/publickey.c:427:7: error: unused parameter 'skeylen' [-Werror,-Wunused-parameter]
        int             skeylen,        /* in  */
                        ^
../key/publickey.c:552:10: error: unused parameter 'from_cache' [-Werror,-Wunused-parameter]
    int *from_cache)    /* in/out  */
         ^

../rpc/xdr_stdio.c:170:22: error: unused parameter 'xdrs' [-Werror,-Wunused-parameter]
xdrstdio_inline(XDR *xdrs, int len)
                     ^
../rpc/xdr_stdio.c:170:32: error: unused parameter 'len' [-Werror,-Wunused-parameter]
xdrstdio_inline(XDR *xdrs, int len)
                               ^
../rpc/xdr_stdio.c:186:23: error: unused parameter 'xdrs' [-Werror,-Wunused-parameter]
xdrstdio_control(XDR *xdrs, int request, void *info)
                      ^
../rpc/xdr_stdio.c:186:33: error: unused parameter 'request' [-Werror,-Wunused-parameter]
xdrstdio_control(XDR *xdrs, int request, void *info)
                                ^
../rpc/xdr_stdio.c:186:48: error: unused parameter 'info' [-Werror,-Wunused-parameter]
xdrstdio_control(XDR *xdrs, int request, void *info)
                                               ^
5 errors generated.

../rpc/xdr_sizeof.c:40:28: error: unused parameter 'ip' [-Werror,-Wunused-parameter]
x_putlong(XDR *xdrs, long *ip)
                           ^
../rpc/xdr_sizeof.c:58:29: error: unused parameter 'bp' [-Werror,-Wunused-parameter]
x_putbytes(XDR *xdrs, char *bp, int len)
                            ^
../rpc/xdr_sizeof.c:72:17: error: unused parameter 'xdrs' [-Werror,-Wunused-parameter]
x_setpostn(XDR *xdrs, uint_t pos)
                ^
../rpc/xdr_sizeof.c:72:30: error: unused parameter 'pos' [-Werror,-Wunused-parameter]
x_setpostn(XDR *xdrs, uint_t pos)
                             ^
4 errors generated.

../rpc/xdr_mem.c:92:21: error: unused parameter 'xdrs' [-Werror,-Wunused-parameter]
xdrmem_destroy(XDR *xdrs)
                    ^
1 error generated.

../rpc/xdr_float.c:104:20: error: unused parameter 'xdrs' [-Werror,-Wunused-parameter]
xdr_quadruple(XDR *xdrs, long double *fp)
                   ^
../rpc/xdr_float.c:104:39: error: unused parameter 'fp' [-Werror,-Wunused-parameter]
xdr_quadruple(XDR *xdrs, long double *fp)
                                      ^
2 errors generated.

../rpc/svc_vc.c:379:37: error: unused parameter 'flag' [-Werror,-Wunused-parameter]
__svc_vc_setflag(SVCXPRT *xprt, int flag)
                                    ^
../rpc/svc_vc.c:666:51: error: unused parameter 'msg' [-Werror,-Wunused-parameter]
rendezvous_request(SVCXPRT *xprt, struct rpc_msg *msg)
                                                  ^
../rpc/svc_vc.c:1139:26: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
rendezvous_stat(SVCXPRT *xprt)
                         ^
3 errors generated.

../rpc/svc_raw.c:132:23: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_stat(SVCXPRT *xprt)
                      ^
../rpc/svc_raw.c:139:23: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_recv(SVCXPRT *xprt, struct rpc_msg *msg)
                      ^
../rpc/svc_raw.c:167:24: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_reply(SVCXPRT *xprt, struct rpc_msg *msg)
                       ^
../rpc/svc_raw.c:199:26: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_getargs(SVCXPRT *xprt, xdrproc_t xdr_args, caddr_t args_ptr)
                         ^
../rpc/svc_raw.c:216:27: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_freeargs(SVCXPRT *xprt, xdrproc_t xdr_args, caddr_t args_ptr)
                          ^
../rpc/svc_raw.c:237:26: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_destroy(SVCXPRT *xprt)
                         ^
../rpc/svc_raw.c:243:26: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_raw_control(SVCXPRT *xprt, const uint_t rq, void *in)
                         ^
../rpc/svc_raw.c:243:55: error: unused parameter 'in' [-Werror,-Wunused-parameter]
svc_raw_control(SVCXPRT *xprt, const uint_t rq, void *in)
                                                      ^
8 errors generated.

../rpc/svc_door.c:226:18: error: unused parameter 'dp' [-Werror,-Wunused-parameter]
    door_desc_t *dp, uint_t n_did)
                 ^
../rpc/svc_door.c:226:29: error: unused parameter 'n_did' [-Werror,-Wunused-parameter]
    door_desc_t *dp, uint_t n_did)
                            ^
../rpc/svc_door.c:568:24: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_door_stat(SVCXPRT *xprt)
                       ^
../rpc/svc_door.c:721:30: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
__svc_get_door_cred(SVCXPRT *xprt, svc_local_cred_t *lcred)
                             ^
../rpc/svc_door.c:737:37: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
__svc_get_door_ucred(const SVCXPRT *xprt, ucred_t *ucp)
                                    ^

../rpc/svc_dg.c:271:22: error: unused parameter 'xprt' [-Werror,-Wunused-parameter]
svc_dg_stat(SVCXPRT *xprt)
                     ^
1 error generated.

../rpc/svc_auth_sys.c:127:33: error: unused parameter 'rqst' [-Werror,-Wunused-parameter]
__svcauth_short(struct svc_req *rqst, struct rpc_msg *msg)
                                ^
../rpc/svc_auth_sys.c:127:55: error: unused parameter 'msg' [-Werror,-Wunused-parameter]
__svcauth_short(struct svc_req *rqst, struct rpc_msg *msg)
                                                      ^
../rpc/svc_auth.c:160:32: error: unused parameter 'rqst' [-Werror,-Wunused-parameter]
__svcauth_null(struct svc_req *rqst, struct rpc_msg *msg)
                               ^
../rpc/svc_auth.c:160:54: error: unused parameter 'msg' [-Werror,-Wunused-parameter]
__svcauth_null(struct svc_req *rqst, struct rpc_msg *msg)
                                                     ^
2 errors generated.

../rpc/svc.c:561:20: error: unused parameter 'auth' [-Werror,-Wunused-parameter]
authany_wrap(AUTH *auth, XDR *xdrs, xdrproc_t xfunc, caddr_t xwhere)
                   ^

../rpc/rpc_soc.c:470:70: error: unused parameter 'nconf' [-Werror,-Wunused-parameter]
rpc_wrap_bcast(char *resultp, struct netbuf *addr, struct netconfig *nconf)
                                                                     ^

../rpc/clnt_vc.c:877:24: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_vc_geterr(CLIENT *cl, struct rpc_err *errp)
                       ^

../rpc/clnt_raw.c:138:58: error: unused parameter 'timeout' [-Werror,-Wunused-parameter]
    xdrproc_t xresults, caddr_t resultsp, struct timeval timeout)
                                                         ^
../rpc/clnt_raw.c:269:25: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_raw_geterr(CLIENT *cl, struct rpc_err *errp)
                        ^
../rpc/clnt_raw.c:276:26: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_raw_freeres(CLIENT *cl, xdrproc_t xdr_res, caddr_t res_ptr)
                         ^
../rpc/clnt_raw.c:295:24: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_raw_abort(CLIENT *cl, struct rpc_err *errp)
                       ^
../rpc/clnt_raw.c:295:44: error: unused parameter 'errp' [-Werror,-Wunused-parameter]
clnt_raw_abort(CLIENT *cl, struct rpc_err *errp)
                                           ^
../rpc/clnt_raw.c:301:26: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_raw_control(CLIENT *cl, int request, char *info)
                         ^
../rpc/clnt_raw.c:301:34: error: unused parameter 'request' [-Werror,-Wunused-parameter]
clnt_raw_control(CLIENT *cl, int request, char *info)
                                 ^
../rpc/clnt_raw.c:301:49: error: unused parameter 'info' [-Werror,-Wunused-parameter]
clnt_raw_control(CLIENT *cl, int request, char *info)
                                                ^
../rpc/clnt_raw.c:308:26: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_raw_destroy(CLIENT *cl)
                         ^
9 errors generated.

../rpc/clnt_door.c:176:55: error: unused parameter 'utimeout' [-Werror,-Wunused-parameter]
        xdrproc_t xresults, caddr_t resultsp, struct timeval utimeout)
                                                             ^
../rpc/clnt_door.c:298:24: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_door_send(CLIENT *cl, rpcproc_t proc, xdrproc_t xargs, caddr_t argsp)
                       ^
../rpc/clnt_door.c:298:38: error: unused parameter 'proc' [-Werror,-Wunused-parameter]
clnt_door_send(CLIENT *cl, rpcproc_t proc, xdrproc_t xargs, caddr_t argsp)
                                     ^
../rpc/clnt_door.c:298:54: error: unused parameter 'xargs' [-Werror,-Wunused-parameter]
clnt_door_send(CLIENT *cl, rpcproc_t proc, xdrproc_t xargs, caddr_t argsp)
                                                     ^
../rpc/clnt_door.c:298:69: error: unused parameter 'argsp' [-Werror,-Wunused-parameter]
clnt_door_send(CLIENT *cl, rpcproc_t proc, xdrproc_t xargs, caddr_t argsp)
                                                                    ^
../rpc/clnt_door.c:312:18: error: unused variable 'cu' [-Werror,-Wunused-variable]
        struct cu_data  *cu = (struct cu_data *)cl->cl_private;
                         ^
../rpc/clnt_door.c:319:27: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_door_freeres(CLIENT *cl, xdrproc_t xdr_res, caddr_t res_ptr)
                          ^
../rpc/clnt_dg.c:687:24: error: unused parameter 'cl' [-Werror,-Wunused-parameter]
clnt_dg_geterr(CLIENT *cl, struct rpc_err *errp)
                       ^
../rpc/clnt_dg.c:710:23: error: unused parameter 'h' [-Werror,-Wunused-parameter]
clnt_dg_abort(CLIENT *h)
                      ^
../rpc/auth_time.c:85:18: error: unused parameter 's' [-Werror,-Wunused-parameter]
alarm_hndler(int s)
                 ^
../rpc/auth_sys.c:238:24: error: unused parameter 'auth' [-Werror,-Wunused-parameter]
authsys_nextverf(AUTH *auth)
                       ^
../rpc/auth_sys.c:283:35: error: unused parameter 'dummy' [-Werror,-Wunused-parameter]
authsys_refresh(AUTH *auth, void *dummy)
                                  ^
2 errors generated.

../rpc/auth_none.c:100:24: error: unused parameter 'client' [-Werror,-Wunused-parameter]
authnone_marshal(AUTH *client, XDR *xdrs)
                       ^
../rpc/auth_none.c:121:21: error: unused parameter 'client' [-Werror,-Wunused-parameter]
authnone_verf(AUTH *client)
                    ^
../rpc/auth_none.c:127:25: error: unused parameter 'client' [-Werror,-Wunused-parameter]
authnone_validate(AUTH *client, struct opaque_auth *opaque)
                        ^
../rpc/auth_none.c:127:53: error: unused parameter 'opaque' [-Werror,-Wunused-parameter]
authnone_validate(AUTH *client, struct opaque_auth *opaque)
                                                    ^
../rpc/auth_none.c:134:24: error: unused parameter 'client' [-Werror,-Wunused-parameter]
authnone_refresh(AUTH *client, void *dummy)
                       ^
../rpc/auth_none.c:134:38: error: unused parameter 'dummy' [-Werror,-Wunused-parameter]
authnone_refresh(AUTH *client, void *dummy)
                                     ^
../rpc/auth_none.c:141:24: error: unused parameter 'client' [-Werror,-Wunused-parameter]
authnone_destroy(AUTH *client)
                       ^
7 errors generated.

../rpc/auth_des.c:234:24: error: unused parameter 'auth' [-Werror,-Wunused-parameter]
authdes_nextverf(AUTH *auth)
                       ^
../rpc/auth_des.c:398:35: error: unused parameter 'dummy' [-Werror,-Wunused-parameter]
authdes_refresh(AUTH *auth, void *dummy)
                                  ^
../nsl/t_error.c:41:30: error: unused parameter 'api_semantics' [-Werror,-Wunused-parameter]
_tx_error(const char *s, int api_semantics)
                             ^
1 error generated.

../nsl/t_rcvreldata.c:51:41: error: unused parameter 'discon' [-Werror,-Wunused-parameter]
_tx_rcvreldata(int fd, struct t_discon *discon, int api_semantics)
                                        ^
1 error generated.

../nsl/_utility.c:505:19: error: unused parameter 'fd' [-Werror,-Wunused-parameter]
_t_alloc_bufs(int fd, struct _ti_user *tiptr, struct T_info_ack *tsap)
                  ^
1 error generated.

../dial/dial.c:136:20: error: unused parameter 's1' [-Werror,-Wunused-parameter]
assert(const char *s1, const char *s2, int i1, const char *s3, int i2)
                   ^
../dial/dial.c:136:36: error: unused parameter 's2' [-Werror,-Wunused-parameter]
assert(const char *s1, const char *s2, int i1, const char *s3, int i2)
                                   ^
../dial/dial.c:136:44: error: unused parameter 'i1' [-Werror,-Wunused-parameter]
assert(const char *s1, const char *s2, int i1, const char *s3, int i2)
                                           ^
../dial/dial.c:136:60: error: unused parameter 's3' [-Werror,-Wunused-parameter]
assert(const char *s1, const char *s2, int i1, const char *s3, int i2)
                                                           ^
../dial/dial.c:136:68: error: unused parameter 'i2' [-Werror,-Wunused-parameter]
assert(const char *s1, const char *s2, int i1, const char *s3, int i2)
                                                                   ^
../dial/dial.c:142:20: error: unused parameter 's1' [-Werror,-Wunused-parameter]
logent(const char *s1, const char *s2)
                   ^
../dial/dial.c:142:36: error: unused parameter 's2' [-Werror,-Wunused-parameter]
logent(const char *s1, const char *s2)
                                   ^

/code/illumos-gate/usr/src/lib/libnsl/dial/callers.c:468:15: error: unused parameter 'flds' [-Werror,-Wunused-parameter]
tlicall(char *flds[], char *dev[])
              ^
In file included from ../dial/dial.c:119:
/code/illumos-gate/usr/src/lib/libnsl/dial/conn.c:532:13: error: unused parameter 'sig' [-Werror,-Wunused-parameter]
alarmtr(int sig)
            ^
/code/illumos-gate/usr/src/lib/libnsl/dial/interface.c:212:12: error: unused parameter 'fd' [-Werror,-Wunused-parameter]
tioctl(int fd, int request, ...)
           ^
/code/illumos-gate/usr/src/lib/libnsl/dial/interface.c:212:20: error: unused parameter 'request' [-Werror,-Wunused-parameter]
tioctl(int fd, int request, ...)
                   ^
/code/illumos-gate/usr/src/lib/libnsl/dial/interface.c:242:15: error: unused parameter 'role' [-Werror,-Wunused-parameter]
tteardown(int role, int fdread, int fdwrite)
              ^
/code/illumos-gate/usr/src/lib/libnsl/dial/interface.c:242:37: error: unused parameter 'fdwrite' [-Werror,-Wunused-parameter]
tteardown(int role, int fdread, int fdwrite)
                                    ^
In file included from ../dial/dial.c:122:
/code/illumos-gate/usr/src/lib/libnsl/dial/line.c:105:34: error: unused parameter 'type' [-Werror,-Wunused-parameter]
fixline(int tty, int spwant, int type)
                                 ^

Change-Id: I2a6167a7960321bc72067b84a30e6772accf4019