fd: this statement may fall through
../../common/io/fd.c:375:7: error: this statement may fall through [-Werror=implicit-fallthrough=]
    if (cmos)
       ^
../../common/io/fd.c:384:3: note: here
   default:  /* need to check .conf file */
   ^~~~~~~
../../common/io/fd.c: In function 'fd_probe':
../../common/io/fd.c:298:6: error: this statement may fall through [-Werror=implicit-fallthrough=]
   if (cmos && (drive_type & 0x0F)) {
      ^
../../common/io/fd.c:308:2: note: here
  default:  /* need to check conf file */
  ^~~~~~~
cc1: all warnings being treated as errors