libdevinfo: variable 'door_error' is used uninitialized
../devinfo_devlink.c:3476:6: error: variable 'door_error' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (door_call(fd, &arg)) {
            ^~~~~~~~~~~~~~~~~~~
../devinfo_devlink.c:3484:6: note: uninitialized use occurs here
        if (door_error)
            ^~~~~~~~~~
../devinfo_devlink.c:3476:2: note: remove the 'if' if its condition is always true
        if (door_call(fd, &arg)) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~
../devinfo_devlink.c:3392:21: note: initialize the variable 'door_error' to silence this warning
        int             fd, door_error;
                                      ^
                                       = 0

Change-Id: I0b18fbdc947fbd35f10db4e9345ab620fb3add47