libdevinfo: missing field initializer
../devinfo_devlink.c:1447:26: error: missing field 'flags' initializer [-Werror,-Wmissing-field-initializers]
        struct tnode tnd = {NULL};
                                ^
../devinfo_devlink.c:1920:23: error: missing field 'fcn' initializer [-Werror,-Wmissing-field-initializers]
        recurse_t rec = {NULL};
                             ^
../devinfo_devlink.c:2055:27: error: missing field 'minor_path' initializer [-Werror,-Wmissing-field-initializers]
        link_desc_t linkd = {NULL};
                                 ^
../devinfo_devlink.c:2153:23: error: missing field 'fcn' initializer [-Werror,-Wmissing-field-initializers]
        recurse_t rec = {NULL};
                             ^
../devinfo_devlink.c:2254:34: error: missing field 'abs_path' initializer [-Werror,-Wmissing-field-initializers]
                struct di_devlink vlink = {NULL};
                                               ^
../devinfo_devlink.c:2290:35: error: missing field 'abs_path' initializer [-Werror,-Wmissing-field-initializers]
                        struct di_devlink vlink = {NULL};
                                                       ^
../devinfo_devlink.c:3641:35: error: missing field 'abs_path' initializer [-Werror,-Wmissing-field-initializers]
                        struct di_devlink vlink = {NULL};
                                                       ^
../devinfo_devlink.c:3677:35: error: missing field 'abs_path' initializer [-Werror,-Wmissing-field-initializers]
                        struct di_devlink vlink = {NULL};
                                                       ^
../devinfo_devlink.c:3756:27: error: missing field 'minor_path' initializer [-Werror,-Wmissing-field-initializers]
        link_desc_t linkd = {NULL};
                                 ^

Change-Id: I57b842d693606ba4eb48c45b9fd0fe722a8455c6