loader: unused parameter
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:71:23: error: unused parameter 'path' [-Werror=unused-parameter]
 null_open(const char *path, struct open_file *f)
                       ^~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:71:47: error: unused parameter 'f' [-Werror=unused-parameter]
 null_open(const char *path, struct open_file *f)
                                               ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_close':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:77:30: error: unused parameter 'f' [-Werror=unused-parameter]
 null_close(struct open_file *f)
                              ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_read':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:83:29: error: unused parameter 'f' [-Werror=unused-parameter]
 null_read(struct open_file *f, void *buf, size_t size, size_t *resid)
                             ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:83:38: error: unused parameter 'buf' [-Werror=unused-parameter]
 null_read(struct open_file *f, void *buf, size_t size, size_t *resid)
                                      ^~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:83:50: error: unused parameter 'size' [-Werror=unused-parameter]
 null_read(struct open_file *f, void *buf, size_t size, size_t *resid)
                                                  ^~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:83:64: error: unused parameter 'resid' [-Werror=unused-parameter]
 null_read(struct open_file *f, void *buf, size_t size, size_t *resid)
                                                                ^~~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_write':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:89:30: error: unused parameter 'f' [-Werror=unused-parameter]
 null_write(struct open_file *f, const void *buf, size_t size, size_t *resid)
                              ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:89:45: error: unused parameter 'buf' [-Werror=unused-parameter]
 null_write(struct open_file *f, const void *buf, size_t size, size_t *resid)
                                             ^~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:89:57: error: unused parameter 'size' [-Werror=unused-parameter]
 null_write(struct open_file *f, const void *buf, size_t size, size_t *resid)
                                                         ^~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:89:71: error: unused parameter 'resid' [-Werror=unused-parameter]
 null_write(struct open_file *f, const void *buf, size_t size, size_t *resid)
                                                                       ^~~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_seek':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:95:29: error: unused parameter 'f' [-Werror=unused-parameter]
 null_seek(struct open_file *f, off_t offset, int where)
                             ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:95:38: error: unused parameter 'offset' [-Werror=unused-parameter]
 null_seek(struct open_file *f, off_t offset, int where)
                                      ^~~~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:95:50: error: unused parameter 'where' [-Werror=unused-parameter]
 null_seek(struct open_file *f, off_t offset, int where)
                                                  ^~~~~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_stat':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:102:29: error: unused parameter 'f' [-Werror=unused-parameter]
 null_stat(struct open_file *f, struct stat *sb)
                             ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:102:45: error: unused parameter 'sb' [-Werror=unused-parameter]
 null_stat(struct open_file *f, struct stat *sb)
                                             ^~
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c: In function 'null_readdir':
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:108:32: error: unused parameter 'f' [-Werror=unused-parameter]
 null_readdir(struct open_file *f, struct dirent *d)
                                ^
/code/illumos-gate/usr/src/boot/lib/libstand/nullfs.c:108:50: error: unused parameter 'd' [-Werror=unused-parameter]
 null_readdir(struct open_file *f, struct dirent *d)
                                                  ^
cc1: all warnings being treated as errors