ipsecesp: unused variables
../../common/inet/ip/ipsecesp.c: In function 'esp_port_freshness':
../../common/inet/ip/ipsecesp.c:1333:11: error: unused variable 'local' [-Werror=unused-variable]
 1333 |  uint16_t local = NEXT_16(ports);
      |           ^~~~~
../../common/inet/ip/ipsecesp.c: In function 'esp_add_sa':
../../common/inet/ip/ipsecesp.c:3335:28: error: variable 'dst' set but not used [-Werror=unused-but-set-variable]
 3335 |  struct sockaddr_in *src, *dst;
      |                            ^~~
../../common/inet/ip/ipsecesp.c:3335:22: error: variable 'src' set but not used [-Werror=unused-but-set-variable]
 3335 |  struct sockaddr_in *src, *dst;
      |                      ^~~
cc1: all warnings being treated as errors
*** Error code 1
make: Fatal error: Command failed for target `obj64/ipsecesp.o'
Current working directory /code/illumos-gate/usr/src/uts/intel/ipsecesp

Change-Id: Ia2d070a95aec0f3dd13ad8e9497a194e3e315ef0