i86xpv/unix: unused variable
../../i86pc/os/lgrpplat.c:307:27: error: unused variable 'lgrp_plat_node_domain' [-Werror,-Wunused-variable]
static node_domain_map_t                lgrp_plat_node_domain[MAX_NODES];
                                        ^
1 error generated.

Change-Id: I5b8cf531300bc1471d374e14a1bd22c5f7d4dc93