libnvpair: unused parameter
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:563:50: error: unused paramete
r 'kmflag' [-Werror,-Wunused-parameter]
nvlist_alloc(nvlist_t **nvlp, uint_t nvflag, int kmflag)
                                                 ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:899:48: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
nvlist_dup(nvlist_t *nvl, nvlist_t **nvlp, int kmflag)
                                               ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2264:48: error: unused parameter 'flag' [-Werror,-Wunused-parameter]
nvlist_merge(nvlist_t *dst, nvlist_t *nvl, int flag)
                                               ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2640:9: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
    int kmflag)
        ^
/code/illumos-gate/usr/src/common/nvpair/nvpair_alloc_fixed.c:99:27: error: unused parameter 'nva' [-Werror,-Wunused-parameter]
nv_fixed_free(nv_alloc_t *nva, void *buf, size_t size)
                          ^
/code/illumos-gate/usr/src/common/nvpair/nvpair_alloc_fixed.c:99:38: error: unused parameter 'buf' [-Werror,-Wunused-parameter]
nv_fixed_free(nv_alloc_t *nva, void *buf, size_t size)
                                     ^
/code/illumos-gate/usr/src/common/nvpair/nvpair_alloc_fixed.c:99:50: error: unused parameter 'size' [-Werror,-Wunused-parameter]
nv_fixed_free(nv_alloc_t *nva, void *buf, size_t size)
                                                 ^
3 errors generated.

../nvpair_alloc_system.c:34:26: error: unused parameter 'nva' [-Werror,-Wunused-parameter]
nv_alloc_sys(nv_alloc_t *nva, size_t size)
                         ^
../nvpair_alloc_system.c:41:25: error: unused parameter 'nva' [-Werror,-Wunused-parameter]
nv_free_sys(nv_alloc_t *nva, void *buf, size_t size)
                        ^
../nvpair_alloc_system.c:41:48: error: unused parameter 'size' [-Werror,-Wunused-parameter]
nv_free_sys(nv_alloc_t *nva, void *buf, size_t size)
                                               ^
3 errors generated.

../libnvpair.c:203:1: error: unused parameter 'private' [-Werror,-Wunused-parame
ter]
NVLIST_PRTFUNC(boolean, int, int, "%d")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:203:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:204:1: error: unused parameter 'private' [-Werror,-Wunused-parame
ter]
NVLIST_PRTFUNC(boolean_value, boolean_t, int, "%d")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:204:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:205:1: error: unused parameter 'private' [-Werror,-Wunused-parame
ter]
NVLIST_PRTFUNC(byte, uchar_t, uchar_t, "0x%2.2x")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:205:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:206:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(int8, int8_t, int, "%d")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:206:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:207:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(uint8, uint8_t, uint8_t, "0x%x")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:206:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:207:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(uint8, uint8_t, uint8_t, "0x%x")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:207:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:208:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(int16, int16_t, int16_t, "%d")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:208:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:209:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(uint16, uint16_t, uint16_t, "0x%x")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:209:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:210:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(int32, int32_t, int32_t, "%d")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:210:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:211:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(uint32, uint32_t, uint32_t, "0x%x")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:211:1: error: unused parameter 'nvl' [-Werror,-Wunused-parameter]
../libnvpair.c:192:15: note: expanded from macro 'NVLIST_PRTFUNC'
    nvlist_t *nvl, const char *name, vtype value) \
              ^
../libnvpair.c:212:1: error: unused parameter 'private' [-Werror,-Wunused-parameter]
NVLIST_PRTFUNC(int64, int64_t, longlong_t, "%lld")
^
../libnvpair.c:191:56: note: expanded from macro 'NVLIST_PRTFUNC'
nvprint_##type_and_variant(nvlist_prtctl_t pctl, void *private, \
                                                       ^
../libnvpair.c:253:44: error: unused parameter 'private' [-Werror,-Wunused-param
eter]
nvprint_nvlist(nvlist_prtctl_t pctl, void *private,
                                           ^
../libnvpair.c:254:15: error: unused parameter 'nvl' [-Werror,-Wunused-parameter
]
    nvlist_t *nvl, const char *name, nvlist_t *value)
              ^
../libnvpair.c:272:51: error: unused parameter 'private' [-Werror,-Wunused-param
eter]
nvaprint_nvlist_array(nvlist_prtctl_t pctl, void *private,
                                                  ^
../libnvpair.c:273:15: error: unused parameter 'nvl' [-Werror,-Wunused-parameter
]
    nvlist_t *nvl, const char *name, nvlist_t **valuep, uint_t count)
              ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:563:50: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
nvlist_alloc(nvlist_t **nvlp, uint_t nvflag, int kmflag)
                                                 ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:899:48: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
nvlist_dup(nvlist_t *nvl, nvlist_t **nvlp, int kmflag)
                                               ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2264:48: error: unused parameter 'flag' [-Werror,-Wunused-parameter]
nvlist_merge(nvlist_t *dst, nvlist_t *nvl, int flag)
                                               ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2640:9: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
    int kmflag)
        ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2702:62: error: unused parameter 'kmflag' [-Werror,-Wunused-parameter]
nvlist_unpack(char *buf, size_t buflen, nvlist_t **nvlp, int kmflag)
                                                             ^
/code/illumos-gate/usr/src/common/nvpair/nvpair.c:2777:32: error: unused parameter 'nvs' [-Werror,-Wunused-parameter]
nvs_native_destroy(nvstream_t *nvs)
                               ^

/code/illumos-gate/usr/src/common/nvpair/fnvpair.c:87:38: error: unused parameter 'size' [-Werror,-Wunused-parameter]
fnvlist_pack_free(char *pack, size_t size)
                                     ^
1 error generated.

Change-Id: Ic79ca865cf6d611f155d5382921f053899bec45b