libsecdb: unused parameter
../common/chkauthattr.c:263:23: error: unused parameter 'name' [-Werror,-Wunused-parameter]
comm2auth(const char *name, kva_t *attr, void *ctxt, void *pres)
                      ^

../common/getexecattr.c:235:39: error: unused parameter 'kva' [-Werror,-Wunused-parameter]
findexecattr(const char *prof, kva_t *kva, void *ctxt, void *res)
                                      ^
1 error generated.

Change-Id: I159546d1eb807a3676a9a7c2d9a0cb4af16289d5