librtld_db: unused parameter
../i386/plt32_resolution.c:144:56: error: unused parameter 'lwpid' [-Werror,-Wunused-parameter]
plt32_resolution(rd_agent_t *rap, psaddr_t pc, lwpid_t lwpid,
                                                       ^
1 error generated.

plt64_resolution.c:51:56: error: unused parameter 'lwpid' [-Werror,-Wunused-parameter]
plt64_resolution(rd_agent_t *rap, psaddr_t pc, lwpid_t lwpid,
                                                       ^
1 error generated.

Change-Id: Iea278e45958f769936639e62aaf9e51f5af7471a