libc: unused parameter
../port/threads/thr.c:2946:17: error: unused parameter 'ulwp' [-Werror,-Wunused-parameter]
_resume(ulwp_t *ulwp, caddr_t sp, int dontsave)
                ^
../port/threads/thr.c:2946:31: error: unused parameter 'sp' [-Werror,-Wunused-parameter]
_resume(ulwp_t *ulwp, caddr_t sp, int dontsave)
                              ^
../port/threads/thr.c:2946:39: error: unused parameter 'dontsave' [-Werror,-Wunused-parameter]
_resume(ulwp_t *ulwp, caddr_t sp, int dontsave)
                                      ^
../port/threads/thr.c:2953:21: error: unused parameter 'oldlwp' [-Werror,-Wunused-parameter]
_resume_ret(ulwp_t *oldlwp)
                    ^
4 errors generated.

Change-Id: I921ae336d0a2fd35dff76e0ebcba1bd7d1b42a5f