dladm: unused label
dladm.c: In function 'print_xaggr_cb':
dladm.c:3181:1: error: label 'err' defined but not used [-Werror=unused-label]
 err:
 ^~~
dladm.c: In function 'print_aggr':
dladm.c:3508:1: error: label 'done' defined but not used [-Werror=unused-label]
 done:
 ^~~~
cc1: all warnings being treated as errors

Change-Id: I9a8add878925d6107be7f5f9ea691c317a6cc2f5