ipw: label 'en_adapter' defined but not used
../../common/io/ipw/ipw2100.c: In function 'ipw2100_config':
../../common/io/ipw/ipw2100.c:1000:1: error: label 'en_adapter' defined but not
used [-Werror=unused-label]
 1000 | en_adapter:
      | ^~~~~~~~~~
cc1: all warnings being treated as errors

Change-Id: I936d3216aa03189bcf0c01e8cd9f85b52983296c