libproc: variable is used uninitialized
../common/Psymtab.c:122:6: error: variable 'addrs' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (P->status.pr_dmodel == PR_MODEL_ILP32) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/Psymtab.c:184:10: note: uninitialized use occurs here
        return (addrs);
                ^~~~~
../common/Psymtab.c:122:2: note: remove the 'if' if its condition is always true
        if (P->status.pr_dmodel == PR_MODEL_ILP32) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/Psymtab.c:119:27: note: initialize the variable 'addrs' to silence this warning
        uintptr_t a, addr, *addrs, last = 0;
                                 ^
                                  = NULL
../common/Psymtab.c:1352:6: error: variable 'elf' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (P->status.pr_dmodel == PR_MODEL_ILP32) {
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/Psymtab.c:1374:10: note: uninitialized use occurs here
        return (elf);
                ^~~
../common/Psymtab.c:1352:2: note: remove the 'if' if its condition is always true
        if (P->status.pr_dmodel == PR_MODEL_ILP32) {
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/Psymtab.c:1339:10: note: initialize the variable 'elf' to silence this warning
        Elf *elf;
                ^
                 = NULL
2 errors generated.

Change-Id: Ie1136f1f2b8fb3f189341477141d7ef265dd3a33