9040 libnsl: unused local typedef in rpc code
../rpc/xdr_sizeof.c: In function 'xdr_sizeof':
../rpc/xdr_sizeof.c:133:21: error: typedef 'dummyfunc3' locally defined but not used [-Werror=unused-local-typedefs]
  typedef  bool_t (* dummyfunc3)(XDR *, int32_t *);
                     ^~~~~~~~~~
cc1: all warnings being treated as errors