12804 sysevent.h: C++11 requires a space between string literal and macro
In file included from /code/illumos-gate/proto/root_i386/usr/include/sys/sunddi.h:54,
                 from /code/illumos-gate/proto/root_i386/usr/include/libdevinfo.h:35,
                 from ../common/HBAPort.cc:42:
/code/illumos-gate/proto/root_i386/usr/include/sys/sysevent.h:76:40: error: C++11 requires a space between str
ing literal and macro [-Werror=c++11-compat]
   76 | #define ILLUMOS_KERN_PUB ILLUMOS_VENDOR":"SE_KERN_PUB
      |                                        ^
cc1plus: all warnings being treated as errors
*** Error code 1
dmake: Warning: Command failed for target `pics/HBAPort.o'
Current working directory /code/illumos-gate/usr/src/lib/sun_fc/i386

Change-Id: I103d6edcd77c14da16ab7f5f6ced1bc524a26fa5