libdisasm: unused parameter
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:1530:32: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_c_name(dis_handle_t *dhp, uint32_t instr,
                               ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:1530:46: error: unused parameter 'instr' [-Werror,-Wunused-parameter]
dis_riscv_c_name(dis_handle_t *dhp, uint32_t instr,
                                             ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:1719:30: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_c_jr(dis_handle_t *dhp, uint32_t instr,
                             ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:1831:34: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_c_bigint(dis_handle_t *dhp, uint32_t instr,
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:1842:31: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_c_int(dis_handle_t *dhp, uint32_t instr,
                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:2129:38: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_min_instrlen(dis_handle_t *dhp)
                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:2136:38: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_max_instrlen(dis_handle_t *dhp)
                                     ^
7 errors generated.

/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:327:34: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_rtype_32(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:413:34: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_utype_32(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:481:29: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_csr(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                            ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:646:31: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fence(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:678:30: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_name(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                             ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:678:44: error: unused parameter 'instr' [-Werror,-Wunused-parameter]
dis_riscv_name(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                           ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:686:33: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_rs1_rs2(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:696:36: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_rv32a_load(dis_handle_t *dhp, uint32_t instr,
                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:716:31: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_rv32a(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:774:30: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_r(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                             ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:788:34: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_r_fpi(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:799:31: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_r4(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:812:35: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_rs2_fp(dis_handle_t *dhp, uint32_t instr, dis_riscv_instr_t *table,
                                  ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:823:38: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_rs2_fp_nr(dis_handle_t *dhp, uint32_t instr,
                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:833:36: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_rs2_fpi(dis_handle_t *dhp, uint32_t instr,
                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:844:36: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_riscv_fp_rs2_ifp(dis_handle_t *dhp, uint32_t instr,
                                   ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1858:19: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_zero(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                  ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1858:37: error: unused parameter 'inst' [-Werror,-Wunused-parameter]
fmt_zero(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                    ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1858:73: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_zero(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1865:19: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_diag(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                  ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1865:73: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_diag(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1873:16: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_e(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
               ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1873:34: error: unused parameter 'inst' [-Werror,-Wunused-parameter]
fmt_e(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1873:46: error: unused parameter 'buf' [-Werror,-Wunused-parameter]
fmt_e(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                             ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1873:58: error: unused parameter 'buflen' [-Werror,-Wunused-parameter]
fmt_e(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                         ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1873:70: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_e(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1880:16: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_i(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
               ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1880:70: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_i(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1887:17: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_ie(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1887:71: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_ie(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                      ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1894:72: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_mii(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                       ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1904:20: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
fmt_ril_a(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1904:74: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_ril_a(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                         ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1912:74: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_ril_b(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                         ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_s390x.c:1922:74: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
fmt_ril_c(uint64_t addr, union inst *inst, char *buf, size_t buflen, int flags)
                                                                         ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:699:68: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_call(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1487:68: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_trap(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1564:68: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
prt_jmpl(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1907:40: error: unused parameter 'instr' [-Werror,-Wunused-parameter]
fmt_regwin(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                       ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1907:70: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_regwin(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1915:72: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_trap_ret(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                       ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1930:69: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_movcc(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                    ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1977:68: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_movr(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                   ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:1999:69: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_fpop1(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                    ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc_fmt.c:2154:69: error: unused parameter 'idx' [-Werror,-Wunused-parameter]
fmt_fused(dis_handle_t *dhp, uint32_t instr, const inst_t *inp, int idx)
                                                                    ^
10 errors generated.

/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:188:38: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_sparc_max_instrlen(dis_handle_t *dhp)
                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:195:38: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_sparc_min_instrlen(dis_handle_t *dhp)
                                     ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:202:35: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_sparc_previnstr(dis_handle_t *dhp, uint64_t pc, int n)
                                  ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:207:9: error: comparison of integers of different signs: 'uint64_t' (aka 'unsigned long long') and 'int' [-Werror,-Wsign-compare]
        if (pc < n)
            ~~ ^ ~
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:215:34: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_sparc_instrlen(dis_handle_t *dhp, uint64_t pc)
                                 ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_sparc.c:215:48: error: unused parameter 'pc' [-Werror,-Wunused-parameter]
dis_sparc_instrlen(dis_handle_t *dhp, uint64_t pc)
                                               ^

/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:3083:45: error: unused parameter 'mode' [-Werror,-Wunused-parameter]
dtrace_rex_adjust(uint_t rex_prefix, uint_t mode, uint_t *reg, uint_t *r_m)
                                            ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:3102:44: error: unused parameter 'mode' [-Werror,-Wunused-parameter]
dtrace_vex_adjust(uint_t vex_byte1, uint_t mode, uint_t *reg, uint_t *r_m)
                                           ^

/code/illumos-gate/usr/src/lib/libdisasm/common/dis_i386.c:163:37: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_i386_max_instrlen(dis_handle_t *dhp)
                                    ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_i386.c:170:37: error: unused parameter 'dhp' [-Werror,-Wunused-parameter]
dis_i386_min_instrlen(dis_handle_t *dhp)
                                    ^
2 errors generated.

/code/illumos-gate/usr/src/lib/libdisasm/common/libdisasm.c:104:28: error: unused parameter 'bytes' [-Werror,-Wunused-parameter]
dis_free(void *ptr, size_t bytes)
                           ^
1 error generated.

Change-Id: I0eb28cd631d4d636dfb85734bc9b3c8e5460f870