libsocket: unused variable
../inet/interface_id.c:227:7: error: unused variable 'index' [-Werror,-Wunused-variable]
        int             index;
                        ^
1 error generated.

Change-Id: Idb691fcb1e956056e0140740cca6741a1570fab4