libuutil: unused parameter
../common/uu_open.c:47:37: error: unused parameter 'uflags' [-Werror,-Wunused-parameter]
uu_open_tmp(const char *dir, uint_t uflags)
                                    ^
1 error generated.

Change-Id: I72f7083d17d3112cc5982002144011684ef6618e