libsaveargs: unused parameter
saveargs.c:201:17: error: unused parameter 'data' [-Werror,-Wunused-parameter]
do_lookup(void *data, uint64_t addr, char *buf, size_t buflen, uint64_t *start,
                ^
saveargs.c:201:32: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
do_lookup(void *data, uint64_t addr, char *buf, size_t buflen, uint64_t *start,
                               ^
saveargs.c:201:44: error: unused parameter 'buf' [-Werror,-Wunused-parameter]
do_lookup(void *data, uint64_t addr, char *buf, size_t buflen, uint64_t *start,
                                           ^
saveargs.c:201:56: error: unused parameter 'buflen' [-Werror,-Wunused-parameter]
do_lookup(void *data, uint64_t addr, char *buf, size_t buflen, uint64_t *start,
                                                       ^
saveargs.c:201:74: error: unused parameter 'start' [-Werror,-Wunused-parameter]
do_lookup(void *data, uint64_t addr, char *buf, size_t buflen, uint64_t *start,
                                                                         ^
saveargs.c:202:13: error: unused parameter 'symlen' [-Werror,-Wunused-parameter]
    size_t *symlen)
            ^

Change-Id: I1f829e675b965e701ecc442e990ff0d8468fc515