libscf: unused label 'error2'
../common/midlevel.c:1801:1: error: unused label 'error2' [-Werror,-Wunused-label]
error2:
^~~~~~~

Change-Id: Iee0e47247c8ecdc4b65af0d5ca5415d2d727d668