libsocket: variable is used uninitialized
../inet/rexec.c:139:7: error: variable 'port' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
                if (getsockname(s2, (struct sockaddr *)&sin2, &sin2len) < 0) {
                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../inet/rexec.c:182:6: note: uninitialized use occurs here
        if (port)
            ^~~~
../inet/rexec.c:139:3: note: remove the 'if' if its condition is always false
                if (getsockname(s2, (struct sockaddr *)&sin2, &sin2len) < 0) {
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../inet/rexec.c:74:15: note: initialize the variable 'port' to silence this warning
        ushort_t port;
                     ^
                      = 0
1 error generated.

Change-Id: If6ba225cafe1d6db1f2c3be17d59b8553962293f