apptrace: unused parameter
../common/apptraceutil.c:193:36: error: unused parameter 'off' [-Werror,-Wunused-parameter]
print_float(ctf_id_t base, ulong_t off, printarg_t *pap)
                                   ^
../common/apptraceutil.c:249:22: error: unused parameter 'base' [-Werror,-Wunused-parameter]
print_array(ctf_id_t base, ulong_t off, printarg_t *pap)
                     ^
../common/apptraceutil.c:259:20: error: unused parameter 'base' [-Werror,-Wunused-parameter]
print_sou(ctf_id_t base, ulong_t off, printarg_t *pap)
                   ^
../common/apptraceutil.c:259:34: error: unused parameter 'off' [-Werror,-Wunused-parameter]
print_sou(ctf_id_t base, ulong_t off, printarg_t *pap)
                                 ^
../common/apptraceutil.c:259:51: error: unused parameter 'pap' [-Werror,-Wunused-parameter]
print_sou(ctf_id_t base, ulong_t off, printarg_t *pap)
                                                  ^
../common/apptraceutil.c:266:35: error: unused parameter 'off' [-Werror,-Wunused-parameter]
print_enum(ctf_id_t base, ulong_t off, printarg_t *pap)
                                  ^
../common/apptraceutil.c:281:20: error: unused parameter 'base' [-Werror,-Wunused-parameter]
print_tag(ctf_id_t base, ulong_t off, printarg_t *pap)
                   ^
../common/apptraceutil.c:281:34: error: unused parameter 'off' [-Werror,-Wunused-parameter]
print_tag(ctf_id_t base, ulong_t off, printarg_t *pap)
                                 ^
../common/apptraceutil.c:281:51: error: unused parameter 'pap' [-Werror,-Wunused-parameter]
print_tag(ctf_id_t base, ulong_t off, printarg_t *pap)
                                                  ^
9 errors generated.

../common/apptrace.c:331:34: error: unused parameter 'lmid' [-Werror,-Wunused-parameter]
la_objopen(Link_map *lmp, Lmid_t lmid, uintptr_t *cookie)
                                 ^
../common/apptrace.c:412:23: error: unused parameter 'cookie' [-Werror,-Wunused-parameter]
la_preinit(uintptr_t *cookie)
                      ^
../common/apptrace.c:480:38: error: unused parameter 'symndx' [-Werror,-Wunused-parameter]
la_symbind32(Elf32_Sym *symp, uint_t symndx, uintptr_t *refcook,
                                     ^
../common/apptrace.c:480:57: error: unused parameter 'refcook' [-Werror,-Wunused-parameter]
la_symbind32(Elf32_Sym *symp, uint_t symndx, uintptr_t *refcook,
                                                        ^
../common/apptrace.c:481:16: error: unused parameter 'defcook' [-Werror,-Wunused-parameter]
    uintptr_t *defcook, uint_t *sb_flags)
               ^
../common/apptrace.c:571:41: error: unused parameter 'symndx' [-Werror,-Wunused-parameter]
la_i86_pltenter(Elf32_Sym *symp, uint_t symndx, uintptr_t *refcookie,
                                        ^
../common/apptrace.c:715:36: error: unused parameter 'symndx' [-Werror,-Wunused-parameter]
la_pltexit(Elf32_Sym *symp, uint_t symndx, uintptr_t *refcookie,
                                   ^
7 errors generated.

Change-Id: If754f4f7b639d339ba4ee6e3e3bb0ab121062086