libc: unused function
../port/stdio/doscan.c:1242:1: error: unused function '_bi_getwc' [-Werror,-Wunused-function]
_bi_getwc(FILE *iop)
^
../port/stdio/doscan.c:1304:1: error: unused function '_bi_ungetwc' [-Werror,-Wunused-function]
_bi_ungetwc(wint_t wc, FILE *iop)
^
2 errors generated.

../port/print/doprnt.c:2688:1: error: unused function '_rec_scrswidth' [-Werror,-Wunused-function]
_rec_scrswidth(wchar_t *wp, ssize_t n)
^
1 error generated.

Change-Id: I10c608878c82eeb655822a965eecaf1798e18f91