svc/startd: unused label
libscf.c: In function 'libscf_read_states':
libscf.c:579:1: error: label 'read_states_out' defined but not used [-Werror=unused-label]
 read_states_out:
 ^~~~~~~~~~~~~~~
libscf.c: In function 'libscf_write_method_status':
libscf.c:2643:1: error: label 'get_pg' defined but not used [-Werror=unused-label]
 get_pg:
 ^~~~~~
cc1: all warnings being treated as errors

fork.c: In function 'emi_is_disabled':
fork.c:925:1: error: label 'out' defined but not used [-Werror=unused-label]
 out:
 ^~~
cc1: all warnings being treated as errors

Change-Id: I190cc2d5aa95235286efc802f37fcb6ac3a7322d