sendmail: assuming signed overflow does not occur
domain.c: In function 'getmxrr':
domain.c:420:2: error: assuming signed overflow does not occur when assuming tha
t (X + c) < X is always false [-Werror=strict-overflow]
  for (i = 0; i < nmx; i++)
  ^~~
cc1: all warnings being treated as errors