ip: unused variables
../../common/inet/udp/udp.c: In function 'udp_srcport_hash':
../../common/inet/udp/udp.c:373:11: error: unused variable 'sap' [-Werror=unused
-variable]
  373 |  uint16_t sap;
      |           ^~~
../../common/inet/udp/udp.c:372:10: error: unused variable 'ipha' [-Werror=unuse
d-variable]
  372 |  ipha_t *ipha;
      |          ^~~~
../../common/inet/udp/udp.c:371:9: error: unused variable 'ip6h' [-Werror=unused
-variable]
  371 |  ip6_t *ip6h;
      |         ^~~~
cc1: all warnings being treated as errors

Change-Id: I4f187044f374ef16df9b458f14cc8d19d28fe001