loader: efinet unused parameter
../efinet.c: In function 'efinet_probe':
../efinet.c:108:28: error: unused parameter 'nif' [-Werror=unused-parameter]
 efinet_probe(struct netif *nif, void *machdep_hint)
                            ^~~
../efinet.c:108:39: error: unused parameter 'machdep_hint' [-Werror=unused-parameter]
 efinet_probe(struct netif *nif, void *machdep_hint)
                                       ^~~~~~~~~~~~
../efinet.c: In function 'efinet_put':
../efinet.c:141:40: error: signed and unsigned type in conditional expression [-Werror=sign-compare]
  return ((status == EFI_SUCCESS) ? len : -1);
                                        ^
../efinet.c: In function 'efinet_init':
../efinet.c:183:40: error: unused parameter 'machdep_hint' [-Werror=unused-parameter]
 efinet_init(struct iodesc *desc, void *machdep_hint)
                                        ^~~~~~~~~~~~
../efinet.c: In function 'efinet_dev_init':
../efinet.c:296:16: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
  for (i = 0; i < sz / sizeof(EFI_HANDLE); i++) {
                ^
cc1: all warnings being treated as errors