libscf: unused parameter
../common/highlevel.c:372:36: error: unused parameter 'hndl' [-Werror,-Wunused-parameter]
scf_default_secflags(scf_handle_t *hndl, scf_secflags_t *flags)
                                   ^
../common/highlevel.c:372:58: error: unused parameter 'flags' [-Werror,-Wunused-parameter]
scf_default_secflags(scf_handle_t *hndl, scf_secflags_t *flags)
                                                         ^

../common/midlevel.c:3132:52: error: unused parameter 'n' [-Werror,-Wunused-parameter]
str_compare(const char *s1, const char *s2, size_t n)
                                                   ^

../common/lowlevel.c:188:71: error: unused parameter 'private' [-Werror,-Wunused-parameter]
transaction_entry_compare(const void *l_arg, const void *r_arg, void *private)
                                                                      ^

Change-Id: Ic378fc9492cedae5e5c38592510273ccc76a4751