libcfgadm: unused label
../common/config_admin.c: In function 'find_lib_hp':
../common/config_admin.c:1732:1: error: label 'fail' defined but not used [-Werror=unused-label]
 1732 | fail:
      | ^~~~
cc1: all warnings being treated as errors

Change-Id: I939737c7ffb7cb6054bca727117deae19e516a84