lofi: unused variable 'id'
../../common/io/lofi.c: In function 'lofi_destroy':
../../common/io/lofi.c:546:6: error: unused variable 'id' [-Werror=unused-variable]
  546 |  int id = LOFI_MINOR2ID(getminor(lsp->ls_dev));
      |      ^~
cc1: all warnings being treated as errors
*** Error code 1
make: Fatal error: Command failed for target `obj64/lofi.o'
Current working directory /code/illumos-gate/usr/src/uts/intel/lofi

Change-Id: I80e07e98e989b3f616c0a708735e6bcd17220ef9