libproc: unused label
64-bit build error:
../common/Psyscall.c:545:1: error: unused label 'bad9' [-Werror,-Wunused-label]
bad9:   Perr++;
^~~~~~~~

Change-Id: I0c351ef7b7cbfcfa5f98dea35819b5c2b216827a