libuutil: missing field 'uap_name' initializer
../common/uu_list.c:60:72: error: missing field 'ulp_name' initializer [-Werror,-Wmissing-field-initializers]
static uu_list_pool_t   uu_null_lpool = { &uu_null_lpool, &uu_null_lpool };
                                                                         ^
1 error generated.

../common/uu_avl.c:33:71: error: missing field 'uap_name' initializer [-Werror,-Wmissing-field-initializers]
static uu_avl_pool_t    uu_null_apool = { &uu_null_apool, &uu_null_apool };
                                                                         ^
1 error generated.

Change-Id: I928a1f895df421f480e574fa601a138a39dad060