libdisasm: missing field
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:954:2: error: missing field 'drv_funct3' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_U32("lui", 0x37),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:876:52: note: expanded from macro 'DIS_RISCV_U32'
        { str, DIS_RISCV_I_U_TYPE, dis_riscv_utype_32, op }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:955:2: error: missing field 'drv_funct3' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_U32("auipc", 0x17),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:876:52: note: expanded from macro 'DIS_RISCV_U32'
        { str, DIS_RISCV_I_U_TYPE, dis_riscv_utype_32, op }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:956:2: error: missing field 'drv_funct3' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_J32("jal", 0x6f),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:878:52: note: expanded from macro 'DIS_RISCV_J32'
        { str, DIS_RISCV_I_J_TYPE, dis_riscv_jtype_32, op }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:958:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_MASK("ret", 0xffffffff, 0x00008067, dis_riscv_name),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:896:48: note: expanded from macro 'DIS_RISCV_MASK'
        { str, DIS_RISCV_I_MASK_TYPE, func, mask, val }
                                                      ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:959:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_I32("jalr", 0x67, 0x0),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:870:56: note: expanded from macro 'DIS_RISCV_I32'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_itype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:960:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("beq", 0x63, 0x0),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:961:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("bne", 0x63, 0x1),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:962:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("blt", 0x63, 0x4),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:963:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("bge", 0x63, 0x5),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:964:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("bltu", 0x63, 0x6),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:965:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_B32("bgeu", 0x63, 0x7),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:874:56: note: expanded from macro 'DIS_RISCV_B32'
        { str, DIS_RISCV_I_B_TYPE, dis_riscv_btype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:966:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_LOAD("lb", 0x03, 0x0),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:893:52: note: expanded from macro 'DIS_RISCV_LOAD'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_load, op, f3 }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:967:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_LOAD("lh", 0x03, 0x1),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:893:52: note: expanded from macro 'DIS_RISCV_LOAD'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_load, op, f3 }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:968:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_LOAD("lw", 0x03, 0x2),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:893:52: note: expanded from macro 'DIS_RISCV_LOAD'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_load, op, f3 }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:969:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_LOAD("lbu", 0x03, 0x4),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:893:52: note: expanded from macro 'DIS_RISCV_LOAD'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_load, op, f3 }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:970:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_LOAD("lhu", 0x03, 0x5),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:893:52: note: expanded from macro 'DIS_RISCV_LOAD'
        { str, DIS_RISCV_I_I_TYPE, dis_riscv_load, op, f3 }
                                                          ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:971:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_S32("sb", 0x23, 0x0),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:872:56: note: expanded from macro 'DIS_RISCV_S32'
        { str, DIS_RISCV_I_S_TYPE, dis_riscv_stype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:972:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_S32("sh", 0x23, 0x1),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:872:56: note: expanded from macro 'DIS_RISCV_S32'
        { str, DIS_RISCV_I_S_TYPE, dis_riscv_stype_32, op, f3 }
                                                              ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:973:2: error: missing field 'drv_funct7' initializer [-Werror,-Wmissing-field-initializers]
        DIS_RISCV_S32("sw", 0x23, 0x2),
        ^
/code/illumos-gate/usr/src/lib/libdisasm/common/dis_riscv.c:872:56: note: expanded from macro 'DIS_RISCV_S32'
        { str, DIS_RISCV_I_S_TYPE, dis_riscv_stype_32, op, f3 }
                                                              ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:563:33: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
const instable_t dis_opMOVSLD = TNS("movslq",MOVSXZ);
                                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:568:32: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
const instable_t dis_opPause = TNS("pause", NORM);
                               ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:573:35: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
const instable_t dis_opWbnoinvd = TNS("wbnoinvd", NORM);
                                  ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:580:13: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNS("sldt",M),          TNS("str",M),           TNSy("lldt",M),         TNSy("ltr",M),
                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:580:29: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNS("sldt",M),          TNS("str",M),           TNSy("lldt",M),         TNSy("ltr",M),
                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:580:44: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNS("sldt",M),          TNS("str",M),           TNSy("lldt",M),         TNSy("ltr",M),
                                                                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:335:60: note: expanded from macro 'TNSy'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:580:61: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNS("sldt",M),          TNS("str",M),           TNSy("lldt",M),         TNSy("ltr",M),
                                                                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:335:60: note: expanded from macro 'TNSy'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:581:13: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("verr",M,2),       TNSZ("verw",M,2),       INVALID,                INVALID,
                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:581:31: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("verr",M,2),       TNSZ("verw",M,2),       INVALID,                INVALID,
                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:581:49: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("verr",M,2),       TNSZ("verw",M,2),       INVALID,                INVALID,
                                                                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:350:52: note: expanded from macro 'INVALID'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:581:59: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("verr",M,2),       TNSZ("verw",M,2),       INVALID,                INVALID,
                                                                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:350:52: note: expanded from macro 'INVALID'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:590:13: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNSZ("sgdt",VMx,6),     TNSZ("sidt",MONITOR_MWAIT,6),   TNSZ("lgdt",XGETBV_XSETBV,6),   TNSZ("lidt",SVM,6),
                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:590:33: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNSZ("sgdt",VMx,6),     TNSZ("sidt",MONITOR_MWAIT,6),   TNSZ("lgdt",XGETBV_XSETBV,6),   TNSZ("lidt",SVM,6),
                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:590:63: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNSZ("sgdt",VMx,6),     TNSZ("sidt",MONITOR_MWAIT,6),   TNSZ("lgdt",XGETBV_XSETBV,6),   TNSZ("lidt",SVM,6),
                                                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:590:93: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [0]  */     TNSZ("sgdt",VMx,6),     TNSZ("sidt",MONITOR_MWAIT,6),   TNSZ("lgdt",XGETBV_XSETBV,6),   TNSZ("lidt",SVM,6),
                                                                                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:591:13: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("smsw",M,2),       INVALID,                TNSZ("lmsw",M,2),       TNS("invlpg",SWAPGS_RDTSCP),
                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:591:31: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("smsw",M,2),       INVALID,                TNSZ("lmsw",M,2),       TNS("invlpg",SWAPGS_RDTSCP),
                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:350:52: note: expanded from macro 'INVALID'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:591:41: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("smsw",M,2),       INVALID,                TNSZ("lmsw",M,2),       TNS("invlpg",SWAPGS_RDTSCP),
                                                                ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:337:64: note: expanded from macro 'TNSZ'
                                                                 ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:591:59: error: missing field 'it_vexwoxmm' initializer [-Werror,-Wmissing-field-initializers]
/*  [4]  */     TNSZ("smsw",M,2),       INVALID,                TNSZ("lmsw",M,2),       TNS("invlpg",SWAPGS_RDTSCP),
                                                                                        ^
/code/illumos-gate/usr/src/common/dis/i386/dis_tables.c:332:59: note: expanded from macro 'TNS'
                                                                 ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.

Change-Id: I333ec2eb976d65357eb45be391ba907866e894ef