libnsl: unused variable
../rpc/clnt_door.c:306:18: error: unused variable 'cu' [-Werror,-Wunused-variable]
        struct cu_data  *cu = (struct cu_data *)cl->cl_private;
                         ^
../rpc/clnt_door.c:324:5: error: explicitly assigning value of variable of type 'CLIENT *' (aka 'struct __client *') to itself [-Werror,-Wself-assign]
        cl = cl;
        ~~ ^ ~~
2 errors generated.

../key/publickey.c:74:19: error: unused variable 'des_caps_str' [-Werror,-Wunused-const-variable]
static const char des_caps_str[] = AUTH_DES_AUTH_TYPE;
                  ^
1 error generated.

../key/publickey.c:437:7: error: unused variable 'rc' [-Werror,-Wunused-variable]
        int             rc = 0;
                        ^
../key/publickey.c:559:6: error: unused variable 'retry_cache' [-Werror,-Wunused-variable]
        int     retry_cache = 0;
                ^
2 errors generated.

Change-Id: I63ef358a7df10c7503e882a23278806bf02dc261