libnvme: conflicting types for 'nvme_log_req_set_csi'
../common/libnvme_log.c:680:1: error: conflicting types for 'nvme_log_req_set_cs
i' due to enum/integer mismatch; have '_Bool(nvme_log_req_t *, uint32_t)' {aka '
_Bool(struct nvme_log_req *, unsigned int)'} [-Werror=enum-int-mismatch]
  680 | nvme_log_req_set_csi(nvme_log_req_t *req, uint32_t csi)
      | ^~~~~~~~~~~~~~~~~~~~
In file included from ../common/libnvme_impl.h:23,
                 from ../common/libnvme_log.c:50:
/code/illumos-gate/proto/root_i386/usr/include/libnvme.h:945:13: note: previous
declaration of 'nvme_log_req_set_csi' with type '_Bool(nvme_log_req_t *, nvme_cs
i_t)' {aka '_Bool(struct nvme_log_req *, nvme_csi_t)'}
  945 | extern bool nvme_log_req_set_csi(nvme_log_req_t *, nvme_csi_t);
      |             ^~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
*** Error code 1
dmake: Warning: Command failed for target `pics/libnvme_log.o'

Change-Id: I