libmp: unused parameter
../common/util.c:51:28: error: unused parameter 's' [-Werror,-Wunused-parameter]
_mp_xalloc(int nint, char *s)
                           ^
1 error generated.

Change-Id: I373c50af90e15bdfc268b36c33c17f07e71c78a1