libuutil: unused function 'uu_init'
../common/uu_misc.c:250:1: error: unused function 'uu_init' [-Werror,-Wunused-function]
uu_init(void)
^
1 error generated.

Change-Id: Idcb9bc1e1a95f287fc07968b1110caf4b1044479