libsmbios: missing field initializer
../../../common/smbios/smb_info.c:233:17: error: missing field 'is_manu' initializer [-Werror,-Wmissing-field-initializers]
        { SMB_TYPE_EOT }
                       ^

Change-Id: I9e769dc3ce5f154484774c20ae873f8106cce0c7