libscf: missing field initializer
../common/scf_tmpl.c:4834:9: error: missing field 'get_val' initializer [-Werror,-Wmissing-field-initializers]
        { NULL }
               ^
1 error generated.

Change-Id: Ibc49358ed027e1e2950f4d6eab802a27978e05b8