unix: unused variable
../../common/os/cpu.c: In function 'cpu_destroy_bound_threads':
../../common/os/cpu.c:3003:14: error: unused variable 'syscid' [-Werror=unused-variable]
 3003 |  extern id_t syscid;
      |              ^~~~~~
cc1: all warnings being treated as errors

Change-Id: I4b3ab0dbf6142b35579cbff6bf7eade2b9b2ee0d