loader: env unused parameter
../env.c: In function 'efi_print_shell_str':
../env.c:377:35: error: unused parameter 'varnamearg' [-Werror=unused-parameter]
 efi_print_shell_str(const CHAR16 *varnamearg, uint8_t *data, UINTN datasz)
                                   ^~~~~~~~~~
../env.c:377:68: error: unused parameter 'datasz' [-Werror=unused-parameter]
 efi_print_shell_str(const CHAR16 *varnamearg, uint8_t *data, UINTN datasz)
                                                                    ^~~~~~
../env.c: In function 'efi_print_mem_type':
../env.c:430:34: error: unused parameter 'varnamearg' [-Werror=unused-parameter]
 efi_print_mem_type(const CHAR16 *varnamearg, uint8_t *data, UINTN datasz)
                                  ^~~~~~~~~~
../env.c: In function 'efi_print_illumos':
../env.c:455:66: error: unused parameter 'datasz' [-Werror=unused-parameter]
 efi_print_illumos(const CHAR16 *varnamearg, uint8_t *data, UINTN datasz)
                                                                  ^~~~~~
../env.c: In function 'efi_print_global':
../env.c:514:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
   for (i = 0; i < datasz / sizeof (UINT16); i++)
                 ^
cc1: all warnings being treated as errors