libmd: unused function 'ROTATE_LEFT'
/code/illumos-gate/usr/src/common/crypto/sha1/sha1.c:118:1: error: unused function 'ROTATE_LEFT' [-Werror,-Wunused-function]
ROTATE_LEFT(uint64_t value, uint32_t n)
^
1 error generated.

Change-Id: Iac52751de1b17f09b728c3efc442ee922691865f