libmapmalloc: unused function 'malloc_init'
../common/textmem.c:290:1: error: unused function 'malloc_init' [-Werror,-Wunused-function]
malloc_init(void)
^
1 error generated.

Change-Id: I37295512b9616850e512dc1725a7668452a82395