libscf: variable is used uninitialized
../common/scf_tmpl.c:1182:6: error: variable 'ret' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (h == NULL)
            ^~~~~~~~~
../common/scf_tmpl.c:1295:6: note: uninitialized use occurs here
        if (ret != SCF_WALK_DONE)
            ^~~
../common/scf_tmpl.c:1182:2: note: remove the 'if' if its condition is always false
        if (h == NULL)
        ^~~~~~~~~~~~~~
../common/scf_tmpl.c:1172:9: note: initialize the variable 'ret' to silence this warning
        int ret;
               ^
                = 0
../common/scf_tmpl.c:1512:6: error: variable 'ret' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (*tmpl_pg_name == NULL)
            ^~~~~~~~~~~~~~~~~~~~~
../common/scf_tmpl.c:1636:6: note: uninitialized use occurs here
        if (ret == SCF_WALK_ERROR)
            ^~~
../common/scf_tmpl.c:1512:2: note: remove the 'if' if its condition is always false
        if (*tmpl_pg_name == NULL)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~
../common/scf_tmpl.c:1479:9: note: initialize the variable 'ret' to silence this warning
        int ret, r;
               ^
                = 0
../common/scf_tmpl.c:2752:12: error: variable 'err' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
                else if (t->pt_svc != NULL)
                         ^~~~~~~~~~~~~~~~~
../common/scf_tmpl.c:2756:7: note: uninitialized use occurs here
                if (err != 0) {
                    ^~~
../common/scf_tmpl.c:2752:8: note: remove the 'if' if its condition is always true
                else if (t->pt_svc != NULL)
                     ^~~~~~~~~~~~~~~~~~~~~~
../common/scf_tmpl.c:2718:9: note: initialize the variable 'err' to silence this warning
        int err;
               ^
                = 0

../common/highlevel.c:178:11: error: missing field 'pv_desc' initializer [-Werror,-Wmissing-field-initializers]
                        { NULL }
                               ^
../common/highlevel.c:238:11: error: missing field 'pv_desc' initializer [-Werror,-Wmissing-field-initializers]
                        { NULL }
                               ^
2 errors generated.

../common/notify_params.c:972:6: error: variable 'count' is used uninitialized whenever 'if' condition is true [-Werror,-Wsometimes-uninitialized]
        if (scf_property_is_type(prop, v->value_type) != SCF_SUCCESS)
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/notify_params.c:1014:19: note: uninitialized use occurs here
        v->value_count = count;
                         ^~~~~
../common/notify_params.c:972:2: note: remove the 'if' if its condition is always false
        if (scf_property_is_type(prop, v->value_type) != SCF_SUCCESS)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../common/notify_params.c:951:25: note: initialize the variable 'count' to silence this warning
        int err, elem_sz, count, cursz;
                               ^
                                = 0

Change-Id: I5c65b62141e588655d69aeb89cc49355ca36ac3f