libproc: unused parameter
Pisadep.c:109:39: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pissyscall_text(struct ps_prochandle *P, const void *buf, size_t buflen)
                                      ^

../common/Putil.c:116:37: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Perror_printf(struct ps_prochandle *P, const char *format, ...)
                                    ^
../common/Putil.c:116:52: error: unused parameter 'format' [-Werror,-Wunused-parameter]
Perror_printf(struct ps_prochandle *P, const char *format, ...)
                                                   ^
2 errors generated.

../common/Psymtab.c:3403:47: error: unused parameter 'P' [-Werror,-Wunused-parameter]
getenv_func(void *data, struct ps_prochandle *P, uintptr_t addr,
                                              ^
../common/Psymtab.c:3403:60: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
getenv_func(void *data, struct ps_prochandle *P, uintptr_t addr,
                                                           ^

../common/Pservice.c:106:43: error: unused parameter 'lwpid' [-Werror,-Wunused-parameter]
ps_lstop(struct ps_prochandle *P, lwpid_t lwpid)
                                          ^
../common/Pservice.c:115:47: error: unused parameter 'lwpid' [-Werror,-Wunused-parameter]
ps_lcontinue(struct ps_prochandle *P, lwpid_t lwpid)
                                              ^
2 errors generated.

../common/Pidle.c:72:35: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pwrite_idle(struct ps_prochandle *P, const void *buf, size_t n, uintptr_t addr,
                                  ^
../common/Pidle.c:72:50: error: unused parameter 'buf' [-Werror,-Wunused-parameter]
Pwrite_idle(struct ps_prochandle *P, const void *buf, size_t n, uintptr_t addr,
                                                 ^
../common/Pidle.c:72:62: error: unused parameter 'n' [-Werror,-Wunused-parameter]
Pwrite_idle(struct ps_prochandle *P, const void *buf, size_t n, uintptr_t addr,
                                                             ^
../common/Pidle.c:72:75: error: unused parameter 'addr' [-Werror,-Wunused-parameter]
Pwrite_idle(struct ps_prochandle *P, const void *buf, size_t n, uintptr_t addr,
                                                                          ^
../common/Pidle.c:73:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pidle.c:81:60: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppriv_idle(struct ps_prochandle *P, prpriv_t **pprv, void *data)
                                                           ^
6 errors generated.

../common/Pgcore.c:900:54: error: unused parameter 'name' [-Werror,-Wunused-parameter]
dump_map(void *data, const prmap_t *pmp, const char *name)
                                                     ^

../common/Pcore.c:125:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pcore.c:133:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pcore.c:141:34: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pcred_core(struct ps_prochandle *P, prcred_t *pcrp, int ngroups, void *data)
                                 ^
../common/Pcore.c:165:38: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Psecflags_core(struct ps_prochandle *P, prsecflags_t **psf, void *data)
                                     ^
../common/Pcore.c:184:34: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Ppriv_core(struct ps_prochandle *P, prpriv_t **pprv, void *data)
                                 ^
../common/Pcore.c:204:49: error: unused parameter 'psinfo' [-Werror,-Wunused-parameter]
Ppsinfo_core(struct ps_prochandle *P, psinfo_t *psinfo, void *data)
                                                ^
../common/Pcore.c:204:63: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppsinfo_core(struct ps_prochandle *P, psinfo_t *psinfo, void *data)
                                                              ^
../common/Pcore.c:211:34: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pfini_core(struct ps_prochandle *P, void *data)
                                 ^
../common/Pcore.c:260:38: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pplatform_core(struct ps_prochandle *P, char *s, size_t n, void *data)
                                     ^
../common/Pcore.c:275:35: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Puname_core(struct ps_prochandle *P, struct utsname *u, void *data)
                                  ^
../common/Pcore.c:289:38: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pzonename_core(struct ps_prochandle *P, char *s, size_t n, void *data)
                                     ^
../common/Pcore.c:304:33: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pldt_core(struct ps_prochandle *P, struct ssd *pldt, int nldt, void *data)
                                ^

../common/proc_fd.c:235:27: error: unused parameter 'type' [-Werror,-Wunused-parameter]
proc_fdinfo_dup_cb(uint_t type, const void *data, size_t len, void *datap)
                          ^
../common/proc_fd.c:235:45: error: unused parameter 'data' [-Werror,-Wunused-parameter]
proc_fdinfo_dup_cb(uint_t type, const void *data, size_t len, void *datap)
                                            ^
2 errors generated.

../common/Pcontrol.c:90:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pcontrol.c:98:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pcontrol.c:106:11: error: unused parameter 'data' [-Werror,-Wunused-parameter]
    void *data)
          ^
../common/Pcontrol.c:139:75: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pread_aux_live(struct ps_prochandle *P, auxv_t **auxvp, int *nauxp, void *data)
                                                                          ^
../common/Pcontrol.c:177:72: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pcred_live(struct ps_prochandle *P, prcred_t *pcrp, int ngroups, void *data)
                                                                       ^
../common/Pcontrol.c:184:67: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Psecflags_live(struct ps_prochandle *P, prsecflags_t **psf, void *data)
                                                                  ^
../common/Pcontrol.c:191:60: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppriv_live(struct ps_prochandle *P, prpriv_t **pprv, void *data)
                                                           ^
../common/Pcontrol.c:206:63: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppsinfo_live(struct ps_prochandle *P, psinfo_t *psinfo, void *data)
                                                              ^
../common/Pcontrol.c:216:46: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Plstatus_live(struct ps_prochandle *P, void *data)
                                             ^
../common/Pcontrol.c:223:46: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Plpsinfo_live(struct ps_prochandle *P, void *data)
                                             ^
../common/Pcontrol.c:230:38: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pplatform_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                     ^
../common/Pcontrol.c:230:66: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pplatform_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                                                 ^
../common/Pcontrol.c:239:35: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Puname_live(struct ps_prochandle *P, struct utsname *u, void *data)
                                  ^
../common/Pcontrol.c:239:63: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Puname_live(struct ps_prochandle *P, struct utsname *u, void *data)
                                                              ^
../common/Pcontrol.c:246:66: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pzonename_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                                                 ^
../common/Pcontrol.c:271:73: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pexecname_live(struct ps_prochandle *P, char *buf, size_t buflen, void *data)
                                                                        ^
../common/Pcontrol.c:319:70: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pldt_live(struct ps_prochandle *P, struct ssd *pldt, int nldt, void *data)
                                                                     ^
../common/Pcontrol.c:136:75: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pread_aux_live(struct ps_prochandle *P, auxv_t **auxvp, int *nauxp, void *data)
                                                                          ^
../common/Pcontrol.c:174:72: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pcred_live(struct ps_prochandle *P, prcred_t *pcrp, int ngroups, void *data)
                                                                       ^
../common/Pcontrol.c:181:67: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Psecflags_live(struct ps_prochandle *P, prsecflags_t **psf, void *data)
                                                                  ^
../common/Pcontrol.c:188:60: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppriv_live(struct ps_prochandle *P, prpriv_t **pprv, void *data)
                                                           ^
../common/Pcontrol.c:203:63: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Ppsinfo_live(struct ps_prochandle *P, psinfo_t *psinfo, void *data)
                                                              ^
../common/Pcontrol.c:213:46: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Plstatus_live(struct ps_prochandle *P, void *data)
                                             ^
../common/Pcontrol.c:220:46: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Plpsinfo_live(struct ps_prochandle *P, void *data)
                                             ^
../common/Pcontrol.c:227:38: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pplatform_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                     ^
../common/Pcontrol.c:227:66: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pplatform_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                                                 ^
../common/Pcontrol.c:236:35: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Puname_live(struct ps_prochandle *P, struct utsname *u, void *data)
                                  ^
../common/Pcontrol.c:236:63: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Puname_live(struct ps_prochandle *P, struct utsname *u, void *data)
                                                              ^
../common/Pcontrol.c:243:66: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pzonename_live(struct ps_prochandle *P, char *s, size_t n, void *data)
                                                                 ^
../common/Pcontrol.c:268:73: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pexecname_live(struct ps_prochandle *P, char *buf, size_t buflen, void *data)
                                                                        ^
../common/Pcontrol.c:316:70: error: unused parameter 'data' [-Werror,-Wunused-parameter]
Pldt_live(struct ps_prochandle *P, struct ssd *pldt, int nldt, void *data)
                                                                     ^
../common/Pcontrol.c:748:40: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Pcreate_callback(struct ps_prochandle *P)
                                       ^
../common/Pcontrol.c:1362:34: error: unused parameter 'P' [-Werror,-Wunused-parameter]
Ppriv_free(struct ps_prochandle *P, prpriv_t *prv)
                                 ^

Change-Id: I7445bfee89aecc914d5fa6148d26da5e2b04fc4c