libc: variable is used uninitialized
../amd64/unwind/eh_frame.c:206:2: error: variable 'res' is used uninitialized whenever switch default is taken [-Werror,-Wsometimes-uninitialized]
        default:
        ^~~~~~~
../amd64/unwind/eh_frame.c:209:10: note: uninitialized use occurs here
        return (res);
                ^~~
../amd64/unwind/eh_frame.c:191:9: note: initialize the variable 'res' to silence this warning
        int res;
               ^
                = 0
1 error generated.

Change-Id: I7c3f7747a7ba2787c10d8bcf3a5971f8718f71f4