libm: unused parameter
../common/m9x/nanl.c:54:20: error: unused parameter 'c' [-Werror,-Wunused-parameter]
__nanl(const char *c) {
                   ^

../common/m9x/nanf.c:41:20: error: unused parameter 'c' [-Werror,-Wunused-parameter]
__nanf(const char *c) {
                   ^
1 error generated.

../common/m9x/nan.c:59:19: error: unused parameter 'c' [-Werror,-Wunused-parameter]
__nan(const char *c) {
                  ^

../common/m9x/__fex_i386.c:238:35: error: unused parameter 'sip' [-Werror,-Wunused-parameter]
__fex_get_invalid_type(siginfo_t *sip, ucontext_t *uap)
                                  ^
1 error generated.

../common/C/matherr.c:36:29: error: unused parameter 'x' [-Werror,-Wunused-parameter]
__matherr(struct exception *x) {
                            ^
1 error generated.

Change-Id: Ia99feb2394c1bc148f17aa036697fa0716ea9230