genunix: unused variable
../../common/contract/device.c: In function 'contract_device_publish':
../../common/contract/device.c:1672:10: error: unused variable 'len' [-Werror=un
used-variable]
 1672 |   size_t len = strlen(path);
      |          ^~~
cc1: all warnings being treated as errors
*** Error code 1
dmake: Warning: Command failed for target `obj64/device.o'
Current working directory /code/illumos-gate/usr/src/uts/intel/genunix

Change-Id: If40258bee60da797eb81c52c069b979ab9c2f539